### PR TITLE
:page_facing_up: Added MIT license

### PR DESCRIPTION
**Pull request by fanurs**

### CODE REVIEW

**Review by PullJosh — APPROVED** [review]
Looks good to me but I know @Owen-Cochell and @Sanya1001 were talking about licensing something last year so check with them first.

**Review by Sanya1001 — APPROVED** [review]

**Comment by Sanya1001** [comment]
We are not using the licensed software so it should be fine. And we will be changing even WebCamJS soon I guess @Owen-Cochell

**Comment by fanurs** [comment]
Just to clarify, this is not for the attendance project, but the special GitHub repo of the organization. (I am mainly wanting to try out PR with multiple reviewers)

**Review by OwenCochell — APPROVED** [review]
Good to test the review feature, just so we know what to expect coming up.

I know that this is not the focus of this test PR, but I don't think we have any licensing issues. All of our main dependencies have very permissive licenses, so in my non-lawyer opinion I think we are okay with using a permissive license like MIT. I will be doing more research on this matter, and I think it would be good to have an understanding of licenses for any future projects.

**Comment by Gabaloo1** [comment]
I agree, I don't foresee any licesing issues. MIT's should do the job, and make us look somewhat more professional.

I love conversations in PR's 😄

**Pull request merged**
